@GoogleKeep.Api_HostAddress = http://localhost:5033

POST {{GoogleKeep.Api_HostAddress}}/api/notes
Accept: application/json
Content-Type: application/json

{
    "title": "New note"    
}
###

GET {{GoogleKeep.Api_HostAddress}}/api/notes/1ee947c0-4985-43eb-86c1-73f7982bfbc4
Accept: application/json

###
