@GoogleKeep.Api_HostAddress = http://localhost:5033

POST {{GoogleKeep.Api_HostAddress}}/api/notes
Accept: application/json
Content-Type: application/json

{
    "title": "New note"    
}
###

GET {{GoogleKeep.Api_HostAddress}}/api/notes/e9bc85b2-3327-41b5-88b7-8673831089
Accept: application/json

###
