@host = http://localhost:5033

# @name login
POST {{host}}/api/authentication/token
Content-Type: application/json
Accept: application/json

{

}

###
POST {{host}}/api/notes
Authorization: Bearer {{login.response.body.token}}
Accept: application/json
Content-Type: application/json

{
    "title": "New note"    
}

###

GET {{host}}/api/notes/1ee947c0-4985-43eb-86c1-73f7982bfbc4
Accept: application/json
Authorization: Bearer {{login.response.body.token}}

###
